# Generated by Django 6.0 on 2026-01-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('guest_count', models.PositiveIntegerField()),
                ('reservation_time', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
